[package]
name = "ruukh-codegen"
version = "0.1.0"
authors = ["Sharad Chand <sharad.d.chand@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.18"
syn = { version = "0.15.1", features = ["full", "extra-traits"] }
quote = "0.6.8"

[dev-dependencies]
ruukh = { path = "../" }
