[package]
name = "dom_ruukh"
version = "0.1.0"
authors = ["Sharad Chand <sharad.d.chand@gmail.com>"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.17"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.2.17"
